### ISSUE TITLE
Publishing to PyPI

### ISSUE THREAD

**Issue by eldruin** [qxcv/pygments-ppddl-lexer#2]
Hi,
Would you be interested in publishing this to [PyPI](https://pypi.org/)?
I found this project almost by chance and I can imagine people need this but did not find it.
I can help you with the packaging and publishing shenanigans if you are interested.

**Comment by qxcv** [comment]
Sure, that sounds good. If you're interested I could transfer the repo to you and you could maintain it? (I'm not doing anything with PDDL right now, so I haven't used this in  a few years)

**Comment by eldruin** [comment]
Ok, yes you can transfer it to me and I will take care of the rest.

**Comment by qxcv** [comment]
I get this error message:

> eldruin/pygments-ppddl-lexer already exists

Unfortunately I don't see a way to transfer under a different name. Maybe you can delete or rename your fork & I can try again?

**Comment by eldruin** [comment]
Alright, done.
Could you try again?

**Comment by qxcv** [comment]
Now I get this error:

> eldruin already has a repository in the qxcv/pygments-ppddl-lexer network

Looks like it has to be deleted entirely. In the mean time I'm going to add you as an admin on this repo, in case you want to push stuff. (edit: particularly to push your own branches before deleting your own copy of the repo, so they don't get lost)

**Comment by eldruin** [comment]
Thanks, I have deleted it now. Hopefully it works this time.

**Comment by qxcv** [comment]
Request sent, should go through when you approve it.

**Comment by eldruin** [comment]
Now it worked, thanks!
